### ISSUE TITLE
How would you test code integrated with SuFile?

### ISSUE THREAD

**Issue by TranceLove** [topjohnwu/libsu#111]
Hello,

I wonder if anyone else writing code with libsu would also write Robolectric test cases to verify behaviour? As one of the developer of https://github.com/TeamAmaze/AmazeFileManager I recently ran into such situation.

Due to the way `ls -a` differs between busybox and bash/zsh I decided to write a `ShadowSuFile` to mock its behaviour. Code is simple enough - I didn't even override anything yet.

```kotlin
import com.topjohnwu.superuser.io.SuFile
import org.robolectric.annotation.Implements
import java.io.File
import java.net.URI

@Implements(SuFile::class)
class ShadowSuFile : SuFile {
    constructor(pathname: String?) : super(pathname)
    constructor(parent: String?, child: String?) : super(parent, child)
    constructor(parent: File?, child: String?) : super(parent, child)
    constructor(uri: URI?) : super(uri)
}
```

But when I ran the test, I got this exception whenever my ShadowSuFile gets loaded with just

```kotlin
import androidx.test.ext.junit.runners.AndroidJUnit4
import ShadowSuFile
import com.topjohnwu.superuser.io.SuFile
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.annotation.Config

@RunWith(AndroidJUnit4::class)
@Config(shadows = [ShadowSuFile::class])
class SimpleTest {

    @Test
    fun testSimple() {
        val file = SuFile.open("/tmp")
    }
}
```

```java
Caused by: java.lang.NegativeArraySizeException: -2
	at org.objectweb.asm.Frame.merge(Frame.java:1222)
	at org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1610)
	at org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1546)
	at org.objectweb.asm.MethodVisitor.visitMaxs(MethodVisitor.java:773)
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:769)
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:649)
	at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:452)
	at org.robolectric.internal.bytecode.ClassInstrumentor.instrumentToBytes(ClassInstrumentor.java:117)
	at org.robolectric.internal.bytecode.ClassInstrumentor.lambda$instrument$1(ClassInstrumentor.java:132)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:53)
	at org.robolectric.internal.bytecode.ClassInstrumentor.instrument(ClassInstrumentor.java:132)
	at org.robolectric.internal.bytecode.SandboxClassLoader.maybeInstrumentClass(SandboxClassLoader.java:153)
	... 21 more
```
(Exception stacktrace is redacted - for details you may look at https://github.com/TeamAmaze/AmazeFileManager/pull/3188#issuecomment-1060872919)

I wonder if it's a bug or there is a workaround for my purpose?

**Comment by topjohnwu** [comment]
Yeah, this is the downside of using Shell I/O, unfortunately the code has only been tested on `busybox` outputs.
My personal suggestion would be to switch to using `RootService` and use actual `File` in the root service for 100% accurate results. I'm leaving this issue open as I still haven't decided on how to deal with this issue

**Comment by vvb2060** [comment]
It looks like it's a problem with robolectric itself when handling SuFile with asm.

**Comment by vvb2060** [comment]
Using SuFile to process files is inefficient and brittle, and it is recommended to use binder for proper IPC instead of STDIO.

An example: https://github.com/zhanghai/MaterialFiles/tree/master/app/src/main/aidl/me/zhanghai/android/files/provider/remote

**Comment by topjohnwu** [comment]
Just a bit more context: the Magisk app is also looking towards switching to use root service IPC for all I/O operations. The `io` module is effectively in maintenance only mode, and will only be tested against `busybox` command outputs

**Comment by topjohnwu** [comment]
Please check out the new `nio` module
