### ISSUE TITLE
Indefinite blocking of thread when denied root permission from SuperSU dialog

### ISSUE THREAD

**Issue by dknchris** [topjohnwu/libsu#14]
Hi,

Great library first of all. I'm the developer of Swift Backup and I recently replaced ChainFire's libsuperuser library to Magisk libsu.

Some testers are still using SuperSU on older devices and Shell.getShell() blocks the thread indefinitely when root is requested and user denies access from the dialog.

This is how I request root access:
```
    public static boolean isAvailable() {
        Log.d(TAG, "isAvailable: Checking");
        Const.checkBackgroundThread();
        IS_ROOTED = Shell.rootAccess();
        return IS_ROOTED;
    }
```
The method never returns the boolean when user denies root access from the request dialog.

Error logs:
```
2018-07-19 14:46:29.281 22307-22375/org.swiftapps.swiftbackup D/LIBSU: Internal Error
    java.io.IOException
        at com.topjohnwu.superuser.internal.ShellImpl.<init>(ShellImpl.java:117)
        at com.topjohnwu.superuser.internal.Factory.createShell(Factory.java:26)
        at com.topjohnwu.superuser.Shell.newInstance(Shell.java:329)
        at com.topjohnwu.superuser.Shell.getShell(Shell.java:261)
        at com.topjohnwu.superuser.Shell.rootAccess(Shell.java:380)
        at org.swiftapps.swiftbackup.common.RootHelper.isAccessGiven(RootHelper.java:48)
        at org.swiftapps.swiftbackup.common.RootHelper.lambda$isAccessGiven$3(RootHelper.java:55)
        at org.swiftapps.swiftbackup.common.-$$Lambda$RootHelper$IFLv8vCPCpKarMRFhE5wv-2MfFs.run(Unknown Source:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
2018-07-19 14:46:29.281 22307-22375/org.swiftapps.swiftbackup D/SHELLIMPL: exec sh
2018-07-19 14:46:29.286 22307-22375/org.swiftapps.swiftbackup D/SHELLIMPL: token: xr85KxwdgoIKRuccWDboKiWO7WbdYTwB
```

**Comment by topjohnwu** [comment]
Thanks for the report, I'll check it out!

**Comment by topjohnwu** [comment]
@dchris87 May you check whether this bug is resolved in `2.0.1`?

**Comment by dchris87** [comment]
@topjohnwu Nope. Still the same behavior. 

TBH, I usually encourage users to use Magisk root and they are very receptive about it. 
You can close the issue IMO since it works very well with magisk root itself. I just don't feel its worth both of our time to fix an issue that is related to a closed source un-maintained root utility as SuperSU.

However, if you feel this issue needs to be resolved, and need more testing I'm happy to help.  Thank you for looking into this!

**Comment by topjohnwu** [comment]
I'm willing to fix it, gonna pull out some old devices that can support SuperSU and test it out LOL

**Comment by dchris87** [comment]
`Column` a is
