### ISSUE TITLE
InvocationTargetException

### ISSUE THREAD

**Issue by D-R-99** [topjohnwu/libsu#145]
Error in IPCMain
java.lang.reflect.InvocationTargetException
 at java.lang.reflect.Method.invoke(Native Method)
 at com.topjohnwu.superuser.internal.RootServerMain.<init>(Unknown Source:6)
 at com.topjohnwu.superuser.internal.RootServerMain.main(Unknown Source:23)
 at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
 at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:338)
Caused by: java.lang.SecurityException: Unable to find app for caller android.app.IApplicationThread$Stub$Proxy@b1ceedf (pid=7309) when getting content provider settings
 at android.os.Parcel.createException(Parcel.java:2087)
 at android.os.Parcel.readException(Parcel.java:2055)
 at android.os.Parcel.readException(Parcel.java:2003)
 at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:5345)
 at android.app.ActivityThread.acquireProvider(ActivityThread.java:6931)
 at android.app.ContextImpl$ApplicationContentResolver.acquireProvider(ContextImpl.java:2826)
 at android.content.ContentResolver.acquireProvider(ContentResolver.java:2242)
 at android.provider.Settings$ContentProviderHolder.getProvider(Settings.java:2241)
 at android.provider.Settings$NameValueCache.getStringForUser(Settings.java:2336)
 at android.provider.Settings$Secure.getStringForUser(Settings.java:5387)
 at android.provider.Settings$Secure.getIntForUser(Settings.java:5565)
 at android.provider.Settings$Secure.getInt(Settings.java:5559)
 at android.view.ColorViewRootUtil.initSwipState(ColorViewRootUtil.java:121)
 at android.view.ViewRootImpl.<init>(ViewRootImpl.java:765)
 at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:382)
 at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:96)
 at com.My.App.AIDLService.onCreate(AIDLService.java:163)
 at com.topjohnwu.superuser.ipc.RootService.attachBaseContext(RootService.java:213)
 ... 5 more
Caused by: android.os.RemoteException: Remote stack trace:
 at com.android.server.am.ActivityManagerService.getContentProviderImpl(ActivityManagerService.java:7342)
 at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:7967)
 at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2201)
 at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2998)
 at com.android.server.am.OppoActivityManagerService.onTransact(OppoActivityManagerService.java:99)

::::
Error While Calling wm.addView(view, params) in RootService

**Comment by topjohnwu** [comment]
The crash happens in your code `AIDLService.onCreate()`, and is not a result of libsu.
