### ISSUE TITLE
RootService: SQLiteDatabase.openDatabase makes it crash

### ISSUE THREAD

**Issue by jacopotediosi** [topjohnwu/libsu#148]
Hi @topjohnwu,
I'm not an Android developer and I'm just learning about AIDL and Bound Services, so I hope I'm not talking nonsense. If so, please let me know if I'm wasting your time.

I'm trying to create an app that needs to modify other apps sqlite databases contained in /data/data. If I understand correctly, Java code executed inside a RootService should be executed in a separate process as root and therefore should be able to access "any" file.

I don't understand why, calling `SQLiteDatabase.openDatabase` from a RootService makes it crash even if the specified database path exists.

To give it a try, I downloaded the sample app code included in this repository and just added the following row in the `getPid()` function within `AIDLService.java`:
```java
@Override
public int getPid() {
            SQLiteDatabase.openDatabase("/data/data/com.google.android.gms/databases/phenotype.db", null, SQLiteDatabase.OPEN_READONLY);
            return Process.myPid();
}
```

Of course, `/data/data/com.google.android.gms/databases/phenotype.db` exists on my filesystem and it's a valid database.
However, clicking the "Bind AIDL" button,  the RootService crashes.

The only logcat I see is the following, which I think just says that the RootService crashed because it failed to access the database file:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.topjohnwu.libsuexample, PID: 639
    java.lang.RuntimeException: Error receiving broadcast Intent { act=com.topjohnwu.superuser.RECEIVER_BROADCAST flg=0x400010 pkg=com.topjohnwu.libsuexample (has extras) } in com.topjohnwu.superuser.internal.RootServiceManager$ServiceReceiver@1a1437c
        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1708)
        at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:210)
        at android.os.Looper.loop(Looper.java:299)
        at android.app.ActivityThread.main(ActivityThread.java:8118)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
     Caused by: java.lang.SecurityException: Unable to find app for caller android.app.IApplicationThread$Stub$Proxy@a3334fc (pid=1451) when getting content provider settings
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
        at android.os.Parcel.createException(Parcel.java:2409)
        at android.os.Parcel.readException(Parcel.java:2392)
        at android.os.Parcel.readException(Parcel.java:2334)
        at com.topjohnwu.libsuexample.ITestService$Stub$Proxy.getPid(ITestService.java:133)
        at com.topjohnwu.libsuexample.MainActivity$AIDLConnection.onServiceConnected(MainActivity.java:98)
        at com.topjohnwu.superuser.internal.RootServiceManager.lambda$bindInternal$2(RootServiceManager.java:268)
        at com.topjohnwu.superuser.internal.RootServiceManager$$ExternalSyntheticLambda2.run(Unknown Source:6)
        at com.topjohnwu.superuser.internal.UiThreadHandler.run(UiThreadHandler.java:31)
        at com.topjohnwu.superuser.internal.UiThreadHandler$$ExternalSyntheticLambda0.execute(Unknown Source:0)
        at com.topjohnwu.superuser.internal.RootServiceManager.bindInternal(RootServiceManager.java:268)
        at com.topjohnwu.superuser.internal.RootServiceManager.lambda$createBindTask$4$com-topjohnwu-superuser-internal-RootServiceManager(RootServiceManager.java:284)
        at com.topjohnwu.superuser.internal.RootServiceManager$$ExternalSyntheticLambda4.run(Unknown Source:8)
        at com.topjohnwu.superuser.internal.RootServiceManager$ServiceReceiver.onReceive(RootServiceManager.java:453)
        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1694)
        at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loopOnce(Looper.java:210) 
        at android.os.Looper.loop(Looper.java:299) 
        at android.app.ActivityThread.main(ActivityThread.java:8118) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045) 
D/OOMEventManagerFK: checkEventAndDumpForJE: 0
I/Process: Sending signal. PID: 639 SIG: 9
```

Maybe I'm missing something?  Otherwise, what other ways would you recommend to access other apps sqlite databases as root? I'm currently using `Shell.cmd()` to command a precompiled sqlite3 binary contained in my app's `dataDir`, but would like to switch to a native approach.

Thanks so much for your time.

**Comment by topjohnwu** [comment]
There are a few things: 
1. You should be looking at the stack trace of the root process, not your app's main process (the log you posted is from your app's main process)
2. It seems to me that `SQLiteDatabase` has some security checks built-in. Since the implementation is part of the Android framework, it is out of your control. So what you should do is to embed your own SQLite library in your app and use it in your root service to access other app's database.

**Comment by jacopotediosi** [comment]
OMG using [SQLite Android Bindings](https://www.sqlite.org/android/doc/trunk/www/index.wiki) worked!
Thanks for the tip about the built-in security checks of `SQLiteDatabase`. I had been going crazy for at least a week.

**Comment by zzzzzzxXxzzzzzz** [comment]
> There are a few things:
> 
> 1. You should be looking at the stack trace of the root process, not your app's main process (the log you posted is from your app's main process)
> 2. It seems to me that `SQLiteDatabase` has some security checks built-in. Since the implementation is part of the Android framework, it is out of your control. So what you should do is to embed your own SQLite library in your app and use it in your root service to access other app's database.

@ #
