### ISSUE TITLE
v1.3.0 NPE when trying to get folder listing

### ISSUE THREAD

**Issue by victorlapin** [topjohnwu/libsu#15]
Simple code to replicate:

val SCRIPT_FILENAME: String = "/cache/recovery/openrecoveryscript"
val scriptFile = SuFile(SCRIPT_FILENAME)
val logFiles = scriptFile.parentFile.listFiles { _, name -> name.endsWith(".log", true) }

v1.2.0 works ok, v1.3.0 throws NullPointerException

UPD: folder you are listing must be empty

**Comment by topjohnwu** [comment]
Thanks for the report, fixed!

**Comment by victorlapin** [comment]
Hate to be that guy, but in v2.0.0 I get IllegalStateException instead of NPE

2018-07-27 19:11:01.900 25947-25947/com.victorlapin.flasher.debug W/RecoveryScriptRepository: java.lang.IllegalStateException
        at java.util.LinkedList$ListItr.remove(LinkedList.java:923)
        at com.topjohnwu.superuser.internal.ShellFile.list(ShellFile.java:299)
        at com.topjohnwu.superuser.internal.ShellFile.listFiles(ShellFile.java:322)
        at com.topjohnwu.superuser.internal.ShellFile.listFiles(ShellFile.java:37)
        at com.topjohnwu.superuser.io.SuFile.listFiles(SuFile.java:273)
