### ISSUE TITLE
NoSuchMethodException on Android 5.1.1

### ISSUE THREAD

**Issue by zhanghai** [topjohnwu/libsu#180]
See https://github.com/zhanghai/MaterialFiles/issues/1161 :

```
W/IPC     ( 4892): Failed to create package context as user: 0
W/IPC     ( 4892): java.lang.NoSuchMethodException: of [int]
W/IPC     ( 4892): 	at java.lang.Class.getDeclaredMethod(Class.java:638)
W/IPC     ( 4892): 	at com.topjohnwu.superuser.internal.RootServerMain.<init>(SourceFile:0)
W/IPC     ( 4892): 	at com.topjohnwu.superuser.internal.RootServerMain.main(SourceFile)
W/IPC     ( 4892): 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
W/IPC     ( 4892): 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:255)
```

**Comment by 3365427906** [comment]
libsu支持Android14吗

**Comment by zhanghai** [comment]
Do you have a plan for releasing this fix?
