### ISSUE TITLE
从IPC中获取ParcelFileDescriptor异常

### ISSUE THREAD

**Issue by LiuJiangshan** [topjohnwu/libsu#65]
ITestService.aidl
```
package com.topjohnwu.libsuexample;
import android.os.ParcelFileDescriptor;
// Declare any non-default types here with import statements

interface ITestService {
    ParcelFileDescriptor getParcelFileDescriptor();
}

```
TestIPC.java
```
class TestIPC extends ITestService.Stub {
    @Override
    public ParcelFileDescriptor getParcelFileDescriptor() throws RemoteException {
        try {
            return ParcelFileDescriptor.open(new File("/data/test/file"), ParcelFileDescriptor.MODE_READ_WRITE);
        } catch (FileNotFoundException e) {
            e.printStackTrace();
            return null;
        }
    }
}
```
当打开方式为可读(ParcelFileDescriptor.MODE_READ_WRITE、ParcelFileDescriptor.MODE_WRITE_ONLY)且文件为ROOT文件会报错
```
15939-16024/com.topjohnwu.libsuexample D/IPC: android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(BinderProxy.java:511)
        at com.topjohnwu.superuser.internal.IRootIPC$Stub$Proxy.bind(IRootIPC.java:151)
        at com.topjohnwu.superuser.ipc.IPCClient.startRootServer(IPCClient.java:145)
        at com.topjohnwu.superuser.ipc.IPCClient.<init>(IPCClient.java:68)
        at com.topjohnwu.superuser.ipc.RootService.lambda$bind$0(RootService.java:109)
        at com.topjohnwu.superuser.ipc.-$$Lambda$RootService$HVE2IJGPdCiSRw2jQKAiHE8PwRk.run(Unknown Source:6)
        at com.topjohnwu.superuser.internal.SerialExecutorService.call(SerialExecutorService.java:51)
        at com.topjohnwu.superuser.internal.SerialExecutorService.call(SerialExecutorService.java:34)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```
如果能直接获取ParcelFileDescriptor，那么就可以使用ParcelFileDescriptor.AutoCloseInputStream、ParcelFileDescriptor.AutoCloseInputStream很方便处理ROOT文件流。

**Comment by LiuJiangshan** [comment]
已解决，关闭selinux
```
adb shell
su
setenforce 0
```
