### ISSUE TITLE
D/LIBSU: Internal Error java.io.IOException: write failed: EPIPE (Broken pipe)

### ISSUE THREAD

**Issue by igor9105** [topjohnwu/libsu#8]
Hello. I got the error when Magisk Manager start.
```
 Supported applets:
06-26 10:20:53.797 10206-10287/com.topjohnwu.magisk D/SHELLOUT:     su, resetprop, magiskhide, imgtool
06-26 10:20:53.798 10206-10287/com.topjohnwu.magisk D/SHELLOUT: sh: <stdin>[457]: }
    : not found
    sh: <stdin>[458]: 
    : not found
    sh: <stdin>[461]: 
     / 100000: unexpected '/'
06-26 10:20:53.800 10206-10206/com.topjohnwu.magisk D/SHELLIMPL: runSyncTask
    runCommands
06-26 10:20:53.802 10206-10206/com.topjohnwu.magisk D/LIBSU: Internal Error
    java.io.IOException: write failed: EPIPE (Broken pipe)
        at libcore.io.IoBridge.write(IoBridge.java:498)
        at java.io.FileOutputStream.write(FileOutputStream.java:186)
        at com.topjohnwu.superuser.internal.ShellImpl$NoCloseOutputStream.write(ShellImpl.java:78)
        at java.io.OutputStream.write(OutputStream.java:82)
        at com.topjohnwu.superuser.internal.ShellImpl.lambda$createCmdTask$5(ShellImpl.java:239)
        at com.topjohnwu.superuser.internal.ShellImpl$$Lambda$3.run(ShellImpl.java)
        at com.topjohnwu.superuser.internal.ShellImpl.lambda$execSyncTask$0(ShellImpl.java:196)
        at com.topjohnwu.superuser.internal.ShellImpl$$Lambda$1.run(ShellImpl.java)
        at com.topjohnwu.superuser.internal.ShellImpl.execTask(ShellImpl.java:177)
        at com.topjohnwu.superuser.internal.ShellImpl.execSyncTask(ShellImpl.java:192)
        at com.topjohnwu.superuser.Shell.run(Shell.java:733)
        at com.topjohnwu.magisk.utils.ShellInitializer.onRootShellInit(ShellInitializer.java:24)
        at com.topjohnwu.superuser.Shell$Initializer.init(Shell.java:979)
        at com.topjohnwu.superuser.Shell$Initializer.access$200(Shell.java:928)
        at com.topjohnwu.superuser.Shell.initShell(Shell.java:807)
        at com.topjohnwu.superuser.Shell.newInstance(Shell.java:350)
        at com.topjohnwu.superuser.Shell.getShell(Shell.java:261)
        at com.topjohnwu.superuser.ShellUtils.fastCmd(ShellUtils.java:91)
        at com.topjohnwu.magisk.MagiskManager.loadMagiskInfo(MagiskManager.java:190)
        at com.topjohnwu.magisk.database.MagiskDatabaseHelper.openDatabase(MagiskDatabaseHelper.java:75)
        at com.topjohnwu.magisk.database.MagiskDatabaseHelper.<init>(MagiskDatabaseHelper.java:54)
        at com.topjohnwu.magisk.database.MagiskDatabaseHelper.getInstance(MagiskDatabaseHelper.java:44)
        at com.topjohnwu.magisk.MagiskManager.onCreate(MagiskManager.java:116)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
        at android.app.ActivityThread.-wrap1(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: android.system.ErrnoException: write failed: EPIPE (Broken pipe)
        at libcore.io.Posix.writeBytes(Native Method)
        at libcore.io.Posix.write(Posix.java:271)
        at libcore.io.BlockGuardOs.write(BlockGuardOs.java:313)
        at libcore.io.IoBridge.write(IoBridge.java:493)
        at java.io.FileOutputStream.write(FileOutputStream.java:186) 
        at com.topjohnwu.superuser.internal.ShellImpl$NoCloseOutputStream.write(ShellImpl.java:78) 
        at java.io.OutputStream.write(OutputStream.java:82) 
        at com.topjohnwu.superuser.internal.ShellImpl.lambda$createCmdTask$5(ShellImpl.java:239) 
        at com.topjohnwu.superuser.internal.ShellImpl$$Lambda$3.run(ShellImpl.java) 
        at com.topjohnwu.superuser.internal.ShellImpl.lambda$execSyncTask$0(ShellImpl.java:196) 
        at com.topjohnwu.superuser.internal.ShellImpl$$Lambda$1.run(ShellImpl.java) 
        at com.topjohnwu.superuser.internal.ShellImpl.execTask(ShellImpl.java:177) 
        at com.topjohnwu.superuser.internal.ShellImpl.execSyncTask(ShellImpl.java:192) 
        at com.topjohnwu.superuser.Shell.run(Shell.java:733) 
        at com.topjohnwu.magisk.utils.ShellInitializer.onRootShellInit(ShellInitializer.java:24) 
        at com.topjohnwu.superuser.Shell$Initializer.init(Shell.java:979) 
        at com.topjohnwu.superuser.Shell$Initializer.access$200(Shell.java:928) 
        at com.topjohnwu.superuser.Shell.initShell(Shell.java:807) 
        at com.topjohnwu.superuser.Shell.newInstance(Shell.java:350) 
        at com.topjohnwu.superuser.Shell.getShell(Shell.java:261) 
        at com.topjohnwu.superuser.ShellUtils.fastCmd(ShellUtils.java:91) 
        at com.topjohnwu.magisk.MagiskManager.loadMagiskInfo(MagiskManager.java:190) 
        at com.topjohnwu.magisk.database.MagiskDatabaseHelper.openDatabase(MagiskDatabaseHelper.java:75) 
        at com.topjohnwu.magisk.database.MagiskDatabaseHelper.<init>(MagiskDatabaseHelper.java:54) 
        at com.topjohnwu.magisk.database.MagiskDatabaseHelper.getInstance(MagiskDatabaseHelper.java:44) 
        at com.topjohnwu.magisk.MagiskManager.onCreate(MagiskManager.java:116) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707) 
        at android.app.ActivityThread.-wrap1(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5417) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
06-26 10:20:53.802 10206-10206/com.topjohnwu.magisk D/SHELLIMPL: close
06-26 10:20:53.803 10206-10206/com.topjohnwu.magisk D/SHELLIMPL: exec su --mount-master
```

**Comment by topjohnwu** [comment]
This seems to be a bug in Magisk Manager, don't report here.
