### ISSUE TITLE
ANR for `Shell.getCachedShell()?.isRoot` ?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [topjohnwu/libsu#87]
implementation "com.github.topjohnwu.libsu:core:3.1.2"

I have a tiny function that I thought that it's safe for any thread I use (including UI thread) :

```
fun hasRoot() = Shell.getCachedShell()?.isRoot == true
```

This tells me if currently I got root capability that I can use.

Recently, Firebase Crashlytics started reporting about ANR cases (only for new Android versions), and I noticed on that gives a clue that might mean the above simple function causes ANR:

```
pool-2-thread-1 (timed waiting): tid=24 systid=13497
       at sun.misc.Unsafe.park(Native method)
       at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
       at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:447)
       at java.util.concurrent.FutureTask.get(FutureTask.java:205)
       at com.topjohnwu.superuser.internal.ShellImpl.<init>(ShellImpl.java:114)
       at com.topjohnwu.superuser.internal.BuilderImpl.build(BuilderImpl.java:77)
       at com.topjohnwu.superuser.internal.BuilderImpl.build(BuilderImpl.java:59)
       at com.topjohnwu.superuser.internal.MainShell.lambda$get$2(MainShell.java:63)
       at com.topjohnwu.superuser.internal.MainShell$$ExternalSyntheticLambda2.run(D8$$SyntheticClass:18446744073709552000)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:920)
```

And:

```
main (unknown): tid=1 systid=12307
       at com.topjohnwu.superuser.internal.MainShell.getCached(MainShell.java:18446744073709552000)
       at com.topjohnwu.superuser.Shell.getCachedShell(Shell.java:199)
....hasRoot...
```

Is it true?
I thought it's safe to use everywhere...
If it's true, is there perhaps an alternative?

**Comment by topjohnwu** [comment]
`MainShell.getCached` will never invoke a new shell creation. The issue you see is caused by shell invocations elsewhere in your app

**Comment by AndroidDeveloperLB** [comment]
@topjohnwu Did I do fine with this tiny function though? Is it safe to use on the UI thread (and any thread) ?
